import {game} from "../sgc/sgc.js";

game.preloadImage("water.png");
game.preloadImage("slider.png");
game.preloadImage("Tile (1).png");
game.preloadImage("Tile (2).png");
game.preloadImage("Tile (3).png");
game.preloadImage("Tile (4).png");
game.preloadImage("TombStone (2).png");
game.preloadImage("wall.png");
game.preloadImage("ann.png", 48, 48);
game.preloadImage("bat.png", 48, 48);
game.preloadImage("spider.png", 48, 48);
game.preloadImage("Graveyard.png");
game.preloadImage("Bone (1).png");
game.preloadImage("Bone (3).png");
game.preloadImage("Tree.png");
game.preloadImage("Tile (14).png");
game.preloadImage("Tile (15).png");
game.preloadImage("Tile (16).png");
game.preloadImage("Crate.png");